services:
  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: 1883
      MQTT_TOPIC_PREFIX: home/iot/v1
      MQTT_CLIENT_ID: iot-worker-dev
      DATABASE_URL: postgresql://${POSTGRES_USER:-iot}:${POSTGRES_PASSWORD:-iot_deb_password}@db:5432/${POSTGRES_DB:-iot}
    depends_on:
      - db
      - mosquitto
  web:
    image: nginx:alpine
    ports:
      - "${API_PORT:-8080}:80"

  client:
    image: curlimages/curl:8.10.1
    command: [ "sleep", "3600" ]

  mosquitto:
    image: eclipse-mosquitto:2.0
    ports:
      - "${MQTT_PORT:-1883}:1883"
    volumes:
      - ./deploy/mosquitto/mosquitto.dev.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mosquitto_sub -h localhost -p 1883 -t 'healthcheck/mosquitto' -C 1 -W 2 >/tmp/mqtt_health.out 2>/dev/null & pid=$$!; sleep 0.2; mosquitto_pub -h localhost -p 1883 -t 'healthcheck/mosquitto' -m 'ping' >/dev/null 2>&1; wait $$pid"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-iot}
      POSTGRES_USER: ${POSTGRES_USER:-iot}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-iot_deb_password}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./deploy/db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-iot} -d ${POSTGRES_DB:-iot} -h localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
# Отладка
  adminer:
    image: adminer:4
    restart: unless-stopped
    ports:
      - "${ADMINER_PORT:-8081}:8080"  
    depends_on:
      - db
  

volumes:
  mosquitto_data:
  mosquitto_log:
  db_data:
